apiVersion: v1
kind: Service
metadata:
  name: hello-world-application
  namespace: hello-world
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ports:
    - name: http
      targetPort: app-port
      port: 8080
  selector:
    app: hello-world-application
  type: ClusterIP
