apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-application
  namespace: openshift-gitops
spec:
  destination:
    namespace:
    server: https://kubernetes.default.svc  
  project: av-dso-poc
  source:
    path: openshift
    repoURL: 'https://github.com/avtarm/Hello-World.git'
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true