name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  APP_NAME: av-dso-poc-py
  APP_PORT: 8080

jobs:

  build-deploy:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - name: Build the Docker image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.APP_NAME }}
        dockerfiles: |
          ./Dockerfile
      
    - name: Log in to docker
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io

    - name: Push To dockerhub
      id: push-to-dockerhub
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        registry: docker.io/avtarmarway/
        
  run-aqua-trivvy-scan:

    runs-on: ubuntu-latest
    needs: build-deploy

    steps:
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/avtarmarway/${{ env.APP_NAME }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL'
        
  run-aqua-chainbench:

    runs-on: ubuntu-latest
    needs: build-deploy

    steps:
    
    - name: Run Trivy chainbench scanner
      id: chain-bench
      uses: ./
      with:
        repository-url: ${{ github.server_url }}/${{ github.repository }}
        github-token: ${{secrets.GITHUB_TOKEN }}

    - name: Echo
      run: echo ${{ steps.chain-bench.outputs.chain-bench-result }}
